### ISSUE TITLE
Command line parameters for picking data source, target column, and model type

### ISSUE THREAD

**Issue by schrum2** [Squillyprice01/KingCreativtiy2019#8]
We should be able to launch our scripts in a manner like this:
``python pandasTry.py data.csv two_year_recid SGDClassifier``
Set up command line parameters for each of these options one by one. Here are some sources you can use:
https://www.pythonforbeginners.com/system/python-sys-argv
https://stackoverflow.com/questions/567879/how-can-i-process-command-line-arguments-in-python

**Comment by Squillyprice01** [comment]
Make it so that each data file has an associated csv with the column names for categorical and numerical feature lists

**Comment by Squillyprice01** [comment]
modelTrain.py works for general cases
